spring:
  application:
    name: microservicio2
  r2dbc:
    url: r2dbc:mysql://database:3306/mydb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

kafka:
  bootstrap-servers: kafka:9092
  topic: my_topic

server:
  port: 8081

logging:
  level:
    root: INFO
    com.microservicio2: DEBUG