spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  application:
    name: microservicio1

  r2dbc:
    url: r2dbc:mysql://127.0.0.1:3306/mydb
    username: user
    password: password



kafka:
  topic: my_topic

server:
  port: 8088

logging:
  level:
    root: INFO
    com.microservicio1: DEBUG
